### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by smaikkeli** [Deeroil/ot-harjoitustyo#1]
Ladattu 8.12 klo 18.58

Pelasin muutaman kierroksen vaihtelevilla ruudukoilla ja peli vaikuttaisi toimivan oikein! Koodi on myös helposti luettavaa, hieman epäselväksi jäi kuitenkin grid-luokan `check_bounds()`-funktio, joka oli tosin vielä työn alla kommenttien perusteella. Funktion eri osat voisi eriytyttää, jos haluaa koodista vielä hieman selkolukuisemman.

Yksi tapa joka voisi helpottaa naapuriruutujen tarkistamista olisi muuttaa lista 2D-matriisiksi, mutta se varmaan on jo käynyt mielessä. Muutenkin monet huomattavat parannusehdotukset ovat jo kommentoituneena johonkin projektissa, joten en näe syytä niiden mainitsemiseen.

Käyttöliittymässä olisi kiva nähdä ruudukon reunoilla ruutujen indeksit, jotta seuraavan siirron valitseminen ei vaatisi ruutujen laskemista.

Olisi kiva jos pelaaja voisi valita joko valmiista ruudukon koista tai sitten omavalintaisesta. En ole itse pelannut paljoa miinaharavaa, joten oli vaikea valita oikean kokoinen ruudukko ja miinojen määrä.

Pidin siitä, kuinka peli on pelattavissa päätteessä. Nämä listapohjaiset pelit on suhteellisen nopea myös toteuttaa esim Pygame-kirjastolla, jotta pelissä olisi myös graafinen käyttöliittymä. Pelin logiikka on jo toimivaa, joten ainoastaan jäljellä olisi ruudukon piirtäminen ja muiden elementtien lisääminen graafiseen käyttöliittymään. Tämä myös helpottaisi ruudukon valitsemista, jolloin pelaaja voisi käyttää hiirtä.

Testit vaikuttavat testaavan kaikki olennaiset toiminnallisuudet, hyvää työtä!

**Comment by Deeroil** [comment]
Kiitos palautteesta! :)

Hyvä pointti, check_bounds() oli hieman hassusti nimetty ja siksi varmaan vielä epäselvempi. Oikeasti se ei tarkistanut ruudukon rajoja, vaan yhden ruudun naapurit. Vaihdoinkin sen nimeksi check_neighbors().

Valmiita ruudukon kokoja teen myöhemmin. katsotaanko teenkö komentorivipuolelle ollenkaan, sain juuri pygamella alustavan GUI:n tehtyä :D
